Rimpiazzare le proposte con degli embed, per #67
AFLdiscord/AFL-Bot pull request #75
Opened 2023-11-16 16:37 UTC by cathartyc

Lo scopo è di impedire la modifica di una proposta inserita, e di rendere più carino il processo in generale.

2023-11-16 16:40 UTC, cathartyc commented
Ci sono altre cose da sistemare, tra cui la gestione degli attachment, la possibilità o meno di cancellare le proposte fatte, etc., e cose che si potrebbero aggiungere come le reaction date automaticamente dal bot per rendere più semplice mettere la reaction.

2023-11-16 17:26 UTC, Skylake-dev requested changes
aggiungere anche la parte di far mettere al bot le reazioni iniziali così che gli utenti possano votare più facilmente

2023-11-16 17:26 UTC, Skylake-dev commented on utils/proposals.py
> +            if message.id not in self.proposals.keys() and not message.author.bot:
commentare cosa significano queste condizioni

2023-11-16 17:26 UTC, Skylake-dev commented on utils/proposals.py
> +            elif len(message.embeds) and message.embeds[0].color == discord.Color.orange():
come sopra

2023-11-16 20:36 UTC, Skylake-dev approved these changes

2023-11-19 22:03 UTC, cathartyc commented
> aggiungere anche la parte di far mettere al bot le reazioni iniziali così che gli utenti possano votare più facilmente

Per il futuro, si potrebbe dare un'occhiata alle [View](https://discordpy.readthedocs.io/en/latest/interactions/api.html#view)

2023-11-20 08:33 UTC, Skylake-dev commented on cogs/events_cog.py
> +            # evitare di loggare due volte un cambio.
penso che questo sia possibile usando le view come dicevi

2023-11-20 08:36 UTC, Skylake-dev approved these changes

2023-11-20 15:57 UTC, merged